name: 'survive_game'
version: 0.0.1
description: Survive Game
author: Pavel Dzunovich <segg3r@gmail.com>

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  stagexl: '0.13.5+1'

transformers:
- dart_to_js_script_rewriter
